format_version: 2
common:
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "APPLY!"
  materials: &materials
    thing:
      type: configrepo
pipelines:
  P:
    group: GOgogadgetCD
    materials:
      <<: *materials
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  Q:
    group: GOgogadgetCD
    materials:
      <<: *materials
      parent:
        pipeline: P
        stage: apply
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  R:
    group: GOgogadgetCD
    materials:
      <<: *materials
      parentTwo:
        pipeline: P
        stage: apply
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
