format_version: 2
common:
  parent: &parent
    Apipeline:
      pipeline: X
      stage: apply
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "APPLY!"
  materials: &materials
    thing:
      type: configrepo
pipelines:
  X:
    group: GOgogadgetCD
    materials:
      <<: *materials
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  Y:
    group: GOgogadgetCD
    materials:
      <<: *materials
      <<: *parent
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  Z:
    group: GOgogadgetCD
    materials:
      <<: *materials
      <<: *parent
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
