format_version: 2
common:
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - exec:
            commond: ls
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - exec:
            commond: ls
  # materials: &materials
  #   thing:
  #     type: configrepo
pipelines:
  Plumbus:
    group: GOgogadgetCD
    materials:
      thing1:
        type: configrepo
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
