format_version: 2
common:
  parent: &parent
    Apipeline:
      pipeline: L
      stage: apply
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual # Require someone in the UI to manually approve the execution of this stage
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "APPLY!"
  materials: &materials
    thing:
      type: configrepo
      destination: repo
pipelines:
  L:
    group: GOgogadgetCD
    materials:
      <<: *materials
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  M:
    group: GOgogadgetCD
    materials:
      <<: *materials
      <<: *parent
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  O:
    group: GOgogadgetCD
    materials:
      <<: *materials
      <<: *parent
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
