format_version: 3
pipelines:
  aTest:
    group: blah
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: git@github.com:ibnc/tablinate.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            run_instances: '0'
            tasks:
            - ant:
                run_if: passed
    parameters:
      hmm: hmm

