format_version: 2
common:
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "x APPLY!"
  # materials: &materials
  #   thing:
  #     type: configrepo
pipelines:
  AAAAA:
    group: GOgogadgetCD
    materials:
      thing1:
        type: configrepo
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  XXXXXXXXXX:
    group: GOgogadgetCD
    materials:
      thing3:
        git: https://github.com/ibnc/tablinate.git
        branch: master
      parent:
        pipeline: AAAAA
        stage: apply
    stages:
      - whatever:
          <<: *plan
  BBBBB:
    group: GOgogadgetCD
    materials:
      thing2:
        type: configrepo
      parent:
        pipeline: AAAAA
        stage: apply
      parent2:
        pipeline: XXXXXXXXXX
        stage: whatever
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
