format_version: 3
pipelines:
  eek_barba_durkle:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    secure_variables:
      ee: ""
    materials:
      git:
        git: git@github.com:ibnc/gogogadgetcd.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - aStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            tasks:
              - exec:
                arguments:
                  - -c
                  - sleep 600
                command: /bin/bash
                run_if: passed
