format_version: 2
common:
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "d APPLY!"
  # materials: &materials
  #   thing:
  #     type: configrepo
pipelines:
  testing:
    group: GOgogadgetCD
    materials:
      thing1:
        type: configrepo
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  eekeek:
    group: GOgogadgetCD
    materials:
      thing3:
        git: https://github.com/ibnc/tablinate.git
        branch: master
    stages:
      - whatever:
          <<: *plan
  blahblah:
    group: GOgogadgetCD
    materials:
      thing2:
        type: configrepo
      parent:
        pipeline: testing
        stage: apply
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
