format_version: 2
common:
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "UPDATING APPLY!"
  # materials: &materials
  #   thing:
  #     type: configrepo
pipelines:
  AAA:
    group: GOgogadgetCD
    materials:
      thing1:
        type: configrepo
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  BBB:
    group: GOgogadgetCD
    materials:
      thing2:
        type: configrepo
      parent:
        pipeline: AAA
        stage: apply
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  CCC:
    group: GOgogadgetCD
    materials:
      thing3:
        type: configrepo
      parentTwo:
        pipeline: AAA
        stage: apply
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
