format_version: 3
pipelines:
  blah:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    secure_variables:
      ee: ""
    materials:
      git:
        git: git@github.com:ibnc/gogogadgetcd.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - '3':
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          '2':
            run_instances: '0'
            tasks:
              - exec:
                  command: /bin/sh
                  arguments: ["-c", "sleep 600"]
