format_version: 2
common:
  plan: &plan
    clean_workspace: true
    jobs:
      plan:
        tasks:
        - script: |
            echo "PLAN!"
  apply: &apply
    approval:
      type: manual
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "f APPLY!"
  # materials: &materials
  #   thing:
  #     type: configrepo
pipelines:
  AAAAA:
    group: GOgogadgetCD
    materials:
      thing1:
        type: configrepo
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  testPipe:
    group: GOgogadgetCD
    materials:
      mygit:
        git: git@github.com:ibnc/tablinate.git
        branch: master
    stages:
      - whatever:
        <<: *plan
  BBBBB:
    group: GOgogadgetCD
    materials:
      thing2:
        type: configrepo
      parent:
        pipeline: AAAAA
        stage: apply
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
