format_version: 3
pipelines:
  blah:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    secure_variables:
      ee: ""
    materials:
      git:
        git: git@github.com:ibnc/tablinate.git
        shallow_clone: false
        auto_update: true
        branch: master
      dependency:
        pipeline: BoB
        stage: defaultStage
    stages:
    - '2':
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          '2':
            run_instances: '0'
            tasks:
            - exec:
                command: echo
                args: $ee
                run_if: passed
  eek:
    group: eekbarbadurkle
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      ee: uuu
    materials:
      git:
        git: git@github.com:ibnc/tablinate.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - '2':
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          '2':
            run_instances: '0'
            tasks:
            - exec:
                command: ls
                run_if: passed
