format_version: 3
pipelines:
  pipeline3:
    group: blah
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: git@github.com:ibnc/tablinate.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stagething:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob1:
            run_instances: '0'
            tasks:
            - exec:
                command: ls
                run_if: passed
