format_version: 3
pipelines:
  thisAndThat:
    group: eekbarbadurkle
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      ee: uuu
    materials:
      git:
        git: git@github.com:ibnc/tablinate.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: false
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: manual
        environment_variables:
          eek: p
        secure_variables:
          eeku: AES:oqD2xYUDANyoPWrMmaJJDQ==:XrMdcBKmft52E84Jqrkm9g==
        jobs:
          defaultJob:
            run_instances: '0'
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
          grr:
            run_instances: '0'
            tasks:
            - exec:
                command: ls
                run_if: passed
    - '2':
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          '2':
            run_instances: '0'
            tasks:
            - exec:
                command: ls
                run_if: passed
    parameters:
      hmm: hmm
      this: that
